//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuzibleService.Languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FuzibleService.Languages.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [FUZIBLE] Abnormal Jobs Queue State. Please Check the Service Application.
        /// </summary>
        public static string svc_abnormalstack_mailobject {
            get {
                return ResourceManager.GetString("svc_abnormalstack_mailobject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Requested Jobs.
        /// </summary>
        public static string svc_abnormalstack_requestedjobs {
            get {
                return ResourceManager.GetString("svc_abnormalstack_requestedjobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Running Jobs.
        /// </summary>
        public static string svc_abnormalstack_runningjobs {
            get {
                return ResourceManager.GetString("svc_abnormalstack_runningjobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can&apos;t launch more Jobs.
        /// </summary>
        public static string svc_cantlaunchmorejobs {
            get {
                return ResourceManager.GetString("svc_cantlaunchmorejobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check &amp; Launch Jobs.
        /// </summary>
        public static string svc_checkandlaunch {
            get {
                return ResourceManager.GetString("svc_checkandlaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending Execution Report.
        /// </summary>
        public static string svc_checkexecutionreport {
            get {
                return ResourceManager.GetString("svc_checkexecutionreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à External Command Ended..
        /// </summary>
        public static string svc_commandended {
            get {
                return ResourceManager.GetString("svc_commandended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Process Exited with non-zero Exit code of: .
        /// </summary>
        public static string svc_commandended_nonzero {
            get {
                return ResourceManager.GetString("svc_commandended_nonzero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service App Crashed : .
        /// </summary>
        public static string svc_crashed {
            get {
                return ResourceManager.GetString("svc_crashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creating SQL Connexion.
        /// </summary>
        public static string svc_createsqlconn {
            get {
                return ResourceManager.GetString("svc_createsqlconn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job Execution Report for the past day.
        /// </summary>
        public static string svc_dailyreport_01 {
            get {
                return ResourceManager.GetString("svc_dailyreport_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à end.
        /// </summary>
        public static string svc_end {
            get {
                return ResourceManager.GetString("svc_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job Ended (.
        /// </summary>
        public static string svc_jobended {
            get {
                return ResourceManager.GetString("svc_jobended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Process was Killed - Timeout.
        /// </summary>
        public static string svc_killedtimeout {
            get {
                return ResourceManager.GetString("svc_killedtimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kill Idle Jobs.
        /// </summary>
        public static string svc_killidle {
            get {
                return ResourceManager.GetString("svc_killidle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  hours).
        /// </summary>
        public static string svc_killidle_hours {
            get {
                return ResourceManager.GetString("svc_killidle_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job Execution Report for the last 24 hours.
        /// </summary>
        public static string svc_last24report_01 {
            get {
                return ResourceManager.GetString("svc_last24report_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Launching External Job.
        /// </summary>
        public static string svc_launchextjob {
            get {
                return ResourceManager.GetString("svc_launchextjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Application Name. Can&apos;t perform operation..
        /// </summary>
        public static string svc_launchextjob_noappname {
            get {
                return ResourceManager.GetString("svc_launchextjob_noappname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Launching Fuzible Job.
        /// </summary>
        public static string svc_launchfuziblejob {
            get {
                return ResourceManager.GetString("svc_launchfuziblejob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must configure an SQL connection before using the Service Application. Please go to the main application, then &apos;Configuration/Service App/&apos;.
        /// </summary>
        public static string svc_mustconfigureservice {
            get {
                return ResourceManager.GetString("svc_mustconfigureservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No user configured for Service App !.
        /// </summary>
        public static string svc_nouser {
            get {
                return ResourceManager.GetString("svc_nouser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Purge History.
        /// </summary>
        public static string svc_purgehistory {
            get {
                return ResourceManager.GetString("svc_purgehistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  day(s)).
        /// </summary>
        public static string svc_purgehistory_days {
            get {
                return ResourceManager.GetString("svc_purgehistory_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job Execution Quantity.
        /// </summary>
        public static string svc_qteexecuted_jobs {
            get {
                return ResourceManager.GetString("svc_qteexecuted_jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checking Queue State (Looking for Excessive Running Jobs).
        /// </summary>
        public static string svc_searchabnormalstackstate {
            get {
                return ResourceManager.GetString("svc_searchabnormalstackstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search &amp; Add Planified Jobs.
        /// </summary>
        public static string svc_searchaddplanified {
            get {
                return ResourceManager.GetString("svc_searchaddplanified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Starting Job.
        /// </summary>
        public static string svc_startingjob {
            get {
                return ResourceManager.GetString("svc_startingjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown Error.
        /// </summary>
        public static string svc_unknowerror {
            get {
                return ResourceManager.GetString("svc_unknowerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Waiting List : .
        /// </summary>
        public static string svc_waitinglist {
            get {
                return ResourceManager.GetString("svc_waitinglist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job Execution Report for the last.
        /// </summary>
        public static string svc_weeklyreport_01 {
            get {
                return ResourceManager.GetString("svc_weeklyreport_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à days.
        /// </summary>
        public static string svc_weeklyreport_02 {
            get {
                return ResourceManager.GetString("svc_weeklyreport_02", resourceCulture);
            }
        }
    }
}
