//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuzibleClient.Languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FuzibleClient.Languages.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check Job Status.
        /// </summary>
        public static string fc_btn_checkstatus {
            get {
                return ResourceManager.GetString("fc_btn_checkstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dynamic Parameters.
        /// </summary>
        public static string fc_btn_dynparams {
            get {
                return ResourceManager.GetString("fc_btn_dynparams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Request.
        /// </summary>
        public static string fc_btn_request {
            get {
                return ResourceManager.GetString("fc_btn_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View Job Queries.
        /// </summary>
        public static string fc_btn_viewqueries {
            get {
                return ResourceManager.GetString("fc_btn_viewqueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Input Password :.
        /// </summary>
        public static string fc_input_pwd {
            get {
                return ResourceManager.GetString("fc_input_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connected to....
        /// </summary>
        public static string fc_lbl_connectedto {
            get {
                return ResourceManager.GetString("fc_lbl_connectedto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of Jobs : .
        /// </summary>
        public static string fc_lbl_listofjobs {
            get {
                return ResourceManager.GetString("fc_lbl_listofjobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scheduled Execution : .
        /// </summary>
        public static string fc_lbl_scheduledexec {
            get {
                return ResourceManager.GetString("fc_lbl_scheduledexec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fuzible Remote Job Launcher.
        /// </summary>
        public static string fc_lbl_title {
            get {
                return ResourceManager.GetString("fc_lbl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fuzible Remote Job Launcher.
        /// </summary>
        public static string fc_lbl_title2 {
            get {
                return ResourceManager.GetString("fc_lbl_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can&apos;t start Job : .
        /// </summary>
        public static string fc_msg_cantrequest {
            get {
                return ResourceManager.GetString("fc_msg_cantrequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connected To.
        /// </summary>
        public static string fc_msg_connectedto {
            get {
                return ResourceManager.GetString("fc_msg_connectedto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flooding Control. You have to wait for .
        /// </summary>
        public static string fc_msg_floodcontrol01 {
            get {
                return ResourceManager.GetString("fc_msg_floodcontrol01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  minutes before launching another iteration..
        /// </summary>
        public static string fc_msg_floodcontrol02 {
            get {
                return ResourceManager.GetString("fc_msg_floodcontrol02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job already invoked/running. Can&apos;t add another instance.
        /// </summary>
        public static string fc_msg_jobalreadyinvoked {
            get {
                return ResourceManager.GetString("fc_msg_jobalreadyinvoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job Description : .
        /// </summary>
        public static string fc_msg_jobdescription {
            get {
                return ResourceManager.GetString("fc_msg_jobdescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Job Selected !.
        /// </summary>
        public static string fc_msg_nojobselected {
            get {
                return ResourceManager.GetString("fc_msg_nojobselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable To Load Selected Job (.
        /// </summary>
        public static string fc_msg_unabletoloadjob {
            get {
                return ResourceManager.GetString("fc_msg_unabletoloadjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to load Job queries : .
        /// </summary>
        public static string fc_msg_unabletoloadjobqueries {
            get {
                return ResourceManager.GetString("fc_msg_unabletoloadjobqueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wrong Password. Can&apos;t Load &amp; Start Job..
        /// </summary>
        public static string fc_wrongpwd01 {
            get {
                return ResourceManager.GetString("fc_wrongpwd01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wrong Password.
        /// </summary>
        public static string fc_wrongpwd02 {
            get {
                return ResourceManager.GetString("fc_wrongpwd02", resourceCulture);
            }
        }
    }
}
