<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net6.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<StartupObject>Fuzible.Program</StartupObject>
		<Platforms>x64</Platforms>
		<ApplicationIcon>hnet.com-image_fat.ico</ApplicationIcon>
		<SignAssembly>false</SignAssembly>
		<DelaySign>false</DelaySign>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<PublishSingleFile>true</PublishSingleFile>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
		<PlatformTarget>x64</PlatformTarget>
		<OutputPath>..\Fuzible\bin\x64\Debug</OutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
	  <Optimize>True</Optimize>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Resources\btn_execute.png" />
	  <None Remove="Resources\btn_loadfile.png" />
	  <None Remove="Resources\btn_save.png" />
	  <None Remove="Resources\btn_stepbystep.png" />
	  <None Remove="Resources\btn_stop.png" />
	  <None Remove="Resources\conn_ad.png" />
	  <None Remove="Resources\conn_db.png" />
	  <None Remove="Resources\conn_file.png" />
	  <None Remove="Resources\conn_mail.png" />
	  <None Remove="Resources\conn_ws.png" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Resources\btn_execute.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\btn_loadfile.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\btn_save.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\btn_stepbystep.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\btn_stop.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\conn_ad.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\conn_db.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\conn_file.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\conn_mail.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\conn_ws.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <EmbeddedResource Include="Resources\Help.db" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="HtmlAgilityPack" Version="1.12.0" />
	  <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
	  <PackageReference Include="MongoDB.Driver" Version="3.3.0" />
	  <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
	  <PackageReference Include="System.Data.Odbc" Version="6.0.2" />
	  <PackageReference Include="System.Data.OleDb" Version="6.0.1" />
	  <PackageReference Include="System.DirectoryServices.AccountManagement" Version="9.0.4" />
	  <PackageReference Include="System.Management" Version="6.0.2" />
	  <PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.4" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\FuzibleFramework\FuzibleFramework.csproj" />
	  <ProjectReference Include="..\FuzibleUITools\FuzibleUITools.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Languages\Languages.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Languages.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Properties\Resources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resources.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Languages\Languages.EN.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Languages\Languages.FR.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Languages\Languages.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>Languages.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Properties\Resources.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

</Project>