<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net6.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<Platforms>x64</Platforms>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
		<PlatformTarget>x64</PlatformTarget>
		<OutputPath>..\Fuzible\bin\x64\Debug</OutputPath>
		<DebugType>none</DebugType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
	  <DebugType>none</DebugType>
	</PropertyGroup>

	<ItemGroup>
	  <Page Update="ComboBoxPrompt.xaml">
	    <SubType>Designer</SubType>
	  </Page>
	  <Page Update="TextContent.xaml">
	    <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
	    <SubType>Designer</SubType>
	  </Page>
	</ItemGroup>

</Project>
